# Generated by Django 6.1.1 on 2026-10-02 15:45

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.BinaryField(blank=True, null=True)),
                ('phone', models.BinaryField(blank=True, null=True)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('role', models.CharField(choices=[('GUEST', 'Guest'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Administrator')], default='GUEST', max_length=8)),
                ('totp_secret', models.BinaryField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
