# Generated by Django 6.1.1 on 2026-10-02 15:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.PROTECT, related_name='occupants', to='gallery.galleryroom'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['GUEST', 'EMPLOYEE', 'ADMIN'])), name='accounts_role_valid'),
        ),
    ]
