# Generated by Django 6.1.1 on 2026-10-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_failed_login_attempts_account_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mfa_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
