# Generated by Django 6.1.1 on 2026-10-02 15:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'gallery_rooms',
            },
        ),
        migrations.CreateModel(
            name='AdjacentRoom',
            fields=[
                ('pk', models.CompositePrimaryKey('room_a', 'room_b', blank=True, editable=False, primary_key=True, serialize=False)),
                ('room_a', models.ForeignKey(db_column='room_a', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gallery.galleryroom')),
                ('room_b', models.ForeignKey(db_column='room_b', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gallery.galleryroom')),
            ],
            options={
                'db_table': 'adjacent_rooms',
                'constraints': [models.CheckConstraint(condition=models.Q(('room_a__lt', models.F('room_b'))), name='adjacent_rooms_ordered')],
            },
        ),
        migrations.CreateModel(
            name='MovementEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('end_room', models.ForeignKey(db_column='end_room', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gallery.galleryroom')),
                ('recorded_by', models.ForeignKey(db_column='recorded_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('start_room', models.ForeignKey(db_column='start_room', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gallery.galleryroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movement_events',
                'indexes': [models.Index(fields=['user', 'event_time'], name='movement_events_user_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_room', models.F('end_room')), _negated=True), name='movement_events_rooms_differ')],
            },
        ),
    ]
