# Generated by Django 6.1.1 on 2026-10-02 15:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_desc', models.BinaryField()),
                ('event_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_log',
                'indexes': [models.Index(fields=['event_time'], name='security_log_time')],
            },
        ),
    ]
